# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bot_service_pb2 as bot__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bot_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinterBotServiceStub(object):
    """General service for MinterMC operations from the SDK
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/MinterBotService/Login',
                request_serializer=bot__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=bot__service__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/MinterBotService/GetStatus',
                request_serializer=bot__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=bot__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.MoveTo = channel.unary_unary(
                '/MinterBotService/MoveTo',
                request_serializer=bot__service__pb2.MoveRequest.SerializeToString,
                response_deserializer=bot__service__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.EventStream = channel.stream_stream(
                '/MinterBotService/EventStream',
                request_serializer=bot__service__pb2.ClientCommand.SerializeToString,
                response_deserializer=bot__service__pb2.ServerEvent.FromString,
                _registered_method=True)


class MinterBotServiceServicer(object):
    """General service for MinterMC operations from the SDK
    """

    def Login(self, request, context):
        """Log in a bot to a specific server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Retrieve the bot's current status and coordinates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveTo(self, request, context):
        """Move the bot to the specified coordinates (Simplified movement API)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request_iterator, context):
        """[IMPORTANT] Event subscription and command sending via bidirectional streaming
        This allows the SDK to hook into asynchronous events such as chat and block breaking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinterBotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=bot__service__pb2.LoginRequest.FromString,
                    response_serializer=bot__service__pb2.LoginResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=bot__service__pb2.StatusRequest.FromString,
                    response_serializer=bot__service__pb2.StatusResponse.SerializeToString,
            ),
            'MoveTo': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTo,
                    request_deserializer=bot__service__pb2.MoveRequest.FromString,
                    response_serializer=bot__service__pb2.MoveResponse.SerializeToString,
            ),
            'EventStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=bot__service__pb2.ClientCommand.FromString,
                    response_serializer=bot__service__pb2.ServerEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MinterBotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MinterBotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MinterBotService(object):
    """General service for MinterMC operations from the SDK
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MinterBotService/Login',
            bot__service__pb2.LoginRequest.SerializeToString,
            bot__service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MinterBotService/GetStatus',
            bot__service__pb2.StatusRequest.SerializeToString,
            bot__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MinterBotService/MoveTo',
            bot__service__pb2.MoveRequest.SerializeToString,
            bot__service__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MinterBotService/EventStream',
            bot__service__pb2.ClientCommand.SerializeToString,
            bot__service__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
